version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - type: "direct"
    ignore:
      # Ignore updates to the symfony/symfony package
      - dependency-name: "symfony/symfony"
